// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// =============================================================================
// license-headers.ts — add/verify the Microsoft MIT license header on every
// first-party source file.
// =============================================================================
// Usage:
//   pnpm headers          # add missing headers in place (idempotent)
//   pnpm headers:check    # verify only; exits non-zero if any file is missing it
//
// The header text is a fixed, well-known constant (deliberately no year, per
// Microsoft OSS guidance) and is inserted with the language-appropriate comment
// style. The add and check modes share the exact same file-selection logic, so
// they can never disagree.
//
// Scope: tracked files (`git ls-files`) with an in-scope extension, excluding
// generated/vendored files. Placement respects a leading shebang and any
// leading directive prologue (e.g. `"use client";`), which stay first.
// =============================================================================

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";

/** The exact two-line header. No year — intentional, matches Microsoft OSS guidance. */
const HEADER_LINES = [
  "Copyright (c) Microsoft Corporation.",
  "Licensed under the MIT License.",
] as const;

/** Extensions that use `//` line comments. */
const LINE_COMMENT_EXTS = new Set(["ts", "tsx", "js", "mjs", "rs", "bicep"]);
/** Extensions that use a `/* ... *\/` block comment. */
const BLOCK_COMMENT_EXTS = new Set(["css"]);
const IN_SCOPE_EXTS = new Set([...LINE_COMMENT_EXTS, ...BLOCK_COMMENT_EXTS]);

/**
 * Vendored / build-output directories. `git ls-files` already omits gitignored
 * paths, but this keeps the selection explicit and robust if any slip in.
 */
const EXCLUDED_DIR_RE = /(^|\/)(node_modules|dist|build|out|target|coverage|\.next)\//;

/**
 * Explicitly excluded individual files. `mockServiceWorker.js` is generated by
 * the `msw` package ("Please do NOT modify this file") — it is third-party, not
 * first-party source, so it must not carry a Microsoft copyright header.
 */
const EXCLUDED_FILES = new Set(["apps/portal/public/mockServiceWorker.js"]);

function extOf(path: string): string {
  const m = /\.([a-z0-9]+)$/i.exec(path);
  return m ? m[1].toLowerCase() : "";
}

function isInScope(path: string): boolean {
  if (path.endsWith(".d.ts")) return false; // generated type declarations
  if (EXCLUDED_FILES.has(path)) return false;
  if (EXCLUDED_DIR_RE.test(path)) return false;
  return IN_SCOPE_EXTS.has(extOf(path));
}

/** Tracked, in-scope files, sorted for deterministic output. */
function listFiles(): string[] {
  const raw = execFileSync("git", ["ls-files", "-z"], { encoding: "buffer" });
  return raw
    .toString("utf8")
    .split("\0")
    .filter(Boolean)
    .filter(isInScope)
    .sort();
}

/** Build the header block for a file's comment style, using the given EOL. */
function headerBlock(ext: string, eol: string): string {
  if (BLOCK_COMMENT_EXTS.has(ext)) {
    return ["/*", ...HEADER_LINES.map((l) => ` * ${l}`), " */"].join(eol);
  }
  return HEADER_LINES.map((l) => `// ${l}`).join(eol);
}

function detectEol(content: string): string {
  const i = content.indexOf("\n");
  return i > 0 && content[i - 1] === "\r" ? "\r\n" : "\n";
}

/**
 * Length of the leading prologue (shebang + directive statements) that must
 * remain at the very top of the file, before the license header.
 */
function prologueLength(content: string): number {
  let idx = 0;
  const shebang = /^#![^\n]*\n/.exec(content);
  if (shebang) idx += shebang[0].length;
  // Directive prologue: contiguous quoted directive statements, e.g. 'use client';
  for (;;) {
    const dir = /^(['"])use [\w-]+\1;?[ \t\r]*\n/.exec(content.slice(idx));
    if (!dir) break;
    idx += dir[0].length;
  }
  return idx;
}

interface Processed {
  changed: boolean;
  content: string;
}

function ensureHeader(path: string, original: string): Processed {
  const ext = extOf(path);
  const eol = detectEol(original);

  // Preserve a byte-order mark if present.
  let bom = "";
  let content = original;
  if (content.charCodeAt(0) === 0xfeff) {
    bom = content[0];
    content = content.slice(1);
  }

  const preLen = prologueLength(content);
  const pre = content.slice(0, preLen);
  const rest = content.slice(preLen);
  const block = headerBlock(ext, eol);

  if (rest.startsWith(block)) {
    return { changed: false, content: original };
  }

  const restBody = rest.replace(/^(?:[ \t]*\r?\n)+/, "");
  const sep = restBody.length ? eol + eol : eol;
  const next = bom + pre + block + sep + restBody;
  return { changed: next !== original, content: next };
}

function main(): void {
  const check = process.argv.includes("--check");
  const files = listFiles();

  const missing: string[] = [];
  const changed: string[] = [];

  for (const file of files) {
    const original = readFileSync(file, "utf8");
    const result = ensureHeader(file, original);
    if (!result.changed) continue;
    if (check) {
      missing.push(file);
    } else {
      writeFileSync(file, result.content);
      changed.push(file);
    }
  }

  if (check) {
    if (missing.length > 0) {
      console.error(
        `✖ ${missing.length} of ${files.length} in-scope file(s) are missing the license header:\n` +
          missing.map((f) => `  ${f}`).join("\n"),
      );
      console.error(
        "\nRun `pnpm headers` to add the Microsoft MIT license header to these files.",
      );
      process.exit(1);
    }
    console.log(`✓ All ${files.length} in-scope files have the license header.`);
    return;
  }

  if (changed.length > 0) {
    console.log(
      `Added the license header to ${changed.length} file(s):\n` +
        changed.map((f) => `  ${f}`).join("\n"),
    );
  }
  console.log(
    `✓ License header present on all ${files.length} in-scope files ` +
      `(${changed.length} updated, ${files.length - changed.length} already had it).`,
  );
}

main();
